# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='jpg/png - file', upload_to='nodeads/static/icons', verbose_name='Photo')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 9, 14, 14, 8, 23, 208743, tzinfo=utc))),
                ('is_modered', models.CharField(choices=[('nl', 'null'), ('fl', 'false'), ('tr', 'true')], default='null', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('icon', models.ImageField(help_text='jpg/png - file', upload_to='nodeads/static/icons', verbose_name='Photo')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nodeads.Group', verbose_name='Parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='element',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='nodeads.Group', verbose_name='Parent'),
        ),
    ]
