# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-06 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='parent',
        ),
        migrations.AddField(
            model_name='element',
            name='group',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relement', to='nodeads.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='element',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 21, 20, 0, 185550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='element',
            name='icon',
            field=models.ImageField(help_text='jpg/png - file', upload_to='c:\\django\\nodeads/static/icons', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='element',
            name='is_modered',
            field=models.CharField(choices=[('null', 'null'), ('false', 'false'), ('true', 'true')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(help_text='jpg/png - file', upload_to='c:\\django\\nodeads/static/icons', verbose_name='Photo'),
        ),
    ]
